import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { AuthProvider } from '@/context/AuthContext';
import ThemeProvider from '@/providers/ThemeProvider';
import ToastProvider from '@/providers/ToastProvider';
import Navbar from '@/components/Mixins/Navbar/Navbar';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Cek Ongkir',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={fontSans.className}>
          <ThemeProvider attribute="class" defaultTheme="light">
            <ToastProvider />

            <Navbar />

            <main className="w-full flex items-center justify-center">
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
